package datamodel.pojo;

import java.io.Serializable;

/**
 *
 * @author Milos
 */
public class SoundMessage implements Serializable {

    private static final long serialVersionUID = 19L;

    private long chId; //-1 means from client to server, otherwise chId generated by the server
    private long timestamp, //-1 means from client to server, otherwise timeStamp of the moment when the server receives the message
            ttl = 2000; //2 seconds TTL
    private Object data; //can carry any type of object. in this program, i used a sound packet, but it could be a string, a chunk of video, ...

    public SoundMessage(long chId, long timestamp, Object data) {
        this.chId = chId;
        this.timestamp = timestamp;
        this.data = data;
    }

    /**
     * @return the chId
     */
    public long getChId() {
        return chId;
    }

    /**
     * @param chId the chId to set
     */
    public void setChId(long chId) {
        this.chId = chId;
    }

    /**
     * @return the timestamp
     */
    public long getTimestamp() {
        return timestamp;
    }

    /**
     * @param timestamp the timestamp to set
     */
    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * @return the ttl
     */
    public long getTtl() {
        return ttl;
    }

    /**
     * @param ttl the ttl to set
     */
    public void setTtl(long ttl) {
        this.ttl = ttl;
    }

    /**
     * @return the data
     */
    public Object getData() {
        return data;
    }

    /**
     * @param data the data to set
     */
    public void setData(Object data) {
        this.data = data;
    }

}
